ALTER TABLE `practices` ADD `mandate_first_name` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `mandate_last_name` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `mandate_birth_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `mandate_birth_city` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `mandate_residence_city` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `mandate_phone` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `mandate_tax_code` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `mandate_id_type` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `mandate_id_number` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `mandate_relationship` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `person_father_name` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `person_mother_name` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `person_profession` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `person_marital_status` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `spouse_name` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `spouse_birth_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `spouse_birth_city` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `spouse_residence_city` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `marriage_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `separation_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `widowed_spouse_death_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `widowed_spouse_death_city` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `transport_departure_place` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `funeral_stop_time` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `body_destination` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `concession_type` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `concession_number` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `crematory_ara` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `billing_name` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `billing_address` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `billing_street_number` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `billing_postal_code` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `billing_city` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `billing_tax_code` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `practices` ADD `billing_phone` text DEFAULT '' NOT NULL;